### ISSUE TITLE
插屏广告，加载成功代理一直回调

### ISSUE THREAD

**Issue by lishuzhi1121** [adxdata/SDK-iOS#1]
插屏广告你们的协议和广点通协议方法名一模一样，代理回调时造成了协议方法自己调自己，死循环回调，拷贝代理方法的时候方法名也改一下啊大哥！

**Comment by adxdata** [comment]
感谢您的 issue ，我们会尽快排查。

**Comment by adxdata** [comment]
> 插屏广告你们的协议和广点通协议方法名一模一样，代理回调时造成了协议方法自己调自己，死循环回调，拷贝代理方法的时候方法名也改一下啊大哥！

感谢您的反馈 ，我们会尽快排查。
